name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Check out tests repository
        uses: actions/checkout@v2

      - name: Clone application repository
        run: git clone https://github.com/automacaohml/helpdesk-page.git

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install application dependencies
        run: |
          cd helpdesk-page
          npm install
      
      - name: Install live-server
        run: npm install -g live-server

      - name: Start frontend with live-server
        run: |
          live-server ./helpdesk-page --port=5500 --no-browser &
          sleep 5

      - name: Start application in background
        run: |
          cd helpdesk-page
          node server.cjs &
        env:
          CI: true

      - name: Install test dependencies
        run: npm install
      
      - name: Ensure Cypress binary has execution permissions
        run: chmod +x ./node_modules/.bin/cypress
      
      - name: Install Cypress binary
        run: npx cypress install

      - name: Run Cypress tests
        run: npm run test

      - name: Verify report file exists
        run: ls -l ./reports/

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Relatório dos testes
          path: ./reports/
